# Generated by Django 5.0.6 on 2024-05-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='health_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_activities',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
