# Generated by Django 5.0.6 on 2024-05-10 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
